### ISSUE TITLE
Instructions Unclear

### ISSUE THREAD

**Issue by DrigonTheSecond** [tung362/RoR2GameModeAPI#1]
I tried putting the RoR2PVP.dll and RoR2GameModeAPI.dll in the plugins folder and it doesn't seem to work,I even tried just extracting them in the plugins folder and still didn't work.
Is there any step im missing

**Comment by Mr-Foxtrot** [comment]
> I tried putting the RoR2PVP.dll and RoR2GameModeAPI.dll in the plugins folder and it doesn't seem to work,I even tried just extracting them in the plugins folder and still didn't work. Is there any step im missing

Both the PVP mod and probably this API is broken due to the Void DLC update from a bit ago. This mod was made before that DLC, which changed a lot about the game. You either gotta wait for this to get updated (if ever) or instead use the somewhat jank King Kombat Arena instead for PVP content:
https://thunderstore.io/package/kinggrinyov/KingKombatArena/

I hope to see this updated and fixed, because as it is neither ROR2PVP or this API load correctly in the latest version.
